### ISSUE TITLE
getting an error git submodule init

### ISSUE THREAD

**Issue by dsisnero** [googleapis/gapic-generator-ruby#1062]
`c:\windows_home\src\ruby_repos\gapic-generator-ruby>git submodule update
Cloning into 'C:/windows_home/src/ruby_repos/gapic-generator-ruby/shared/api-common-protos'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:googleapis/api-common-protos.git' into submodule path 'C:/windows_home/src/ruby_repos/gapic-generator-ruby/shared/api-common-protos' failed
Failed to clone 'shared/api-common-protos'. Retry scheduled
Cloning into 'C:/windows_home/src/ruby_repos/gapic-generator-ruby/shared/gapic-showcase'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:googleapis/gapic-showcase.git' into submodule path 'C:/windows_home/src/ruby_repos/gapic-generator-ruby/shared/gapic-showcase' failed
Failed to clone 'shared/gapic-showcase'. Retry scheduled
Cloning into 'C:/windows_home/src/ruby_repos/gapic-generator-ruby/shared/googleapis'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:googleapis/googleapis.git' into submodule path 'C:/windows_home/src/ruby_repos/gapic-generator-ruby/shared/googleapis' failed
Failed to clone 'shared/googleapis'. Retry scheduled
Cloning into 'C:/windows_home/src/ruby_repos/gapic-generator-ruby/shared/api-common-protos'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:googleapis/api-common-protos.git' into submodule path 'C:/windows_home/src/ruby_repos/gapic-generator-ruby/shared/api-common-protos' failed
Failed to clone 'shared/api-common-protos' a second time, aborting`

**Comment by dazuma** [comment]
This looks like you don't have an SSH key set up with github. The submodules assume you can access repositories via an SSH-style URL.

Also, the generator does not support Windows. The only platform currently supported is linux on x86-64.
