### ISSUE TITLE
Favor class methods over constants?

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#122]
One of the issues we've been running into with the Rubocop style guidelines is that they want to freeze anything in a constant. But, we have been using constants as a sort of global variable, something for users to change to customize the behavior. `Client::SERVICE_ADDRESS`, `Client::GRPC_INTERCEPTORS`, `Credentials::PATH_ENV_VARS`, etc.

In each of those instances, the constant is considered part of the public API. What is everyone's opinion of using class methods in those instances, and leaving constants for things that are not meant to be changed?

**Comment by jbolinger** [comment]
I always thought that these would be better as constructor parameters. I'd be perfectly happy with class methods though too, and I do like that approach better than the constants.

**Comment by blowmage** [comment]
I think they need to be both, honestly. Someplace to configure a global default, but then allow for overriding when creating the client object.

**Comment by jbolinger** [comment]
Good point 👍you have my vote.

**Comment by quartzmo** [comment]
Agreed. We shouldn't use constants this way, and this usage should be replaced with class methods and constructor options.

**Comment by samphippen** [comment]
👍
