### ISSUE TITLE
Documentation directory outside of lib?

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#123]
The generator currently creates a bunch of documentation files in the `/lib/doc` directory. This location should be fine, as we are not expecting anyone to require those file paths. However, it is still possible. Currently we have added a `raise` statement with an error message stating that these files are not intended to be loaded. That said, what about placing this directory outside of `/lib`, and configuring the `.yardoc` file to load the files in that directory as well? That would allow YARD to know about the documentation, but avoid the issues of accidentally requiring the files. Thoughts?

**Comment by jbolinger** [comment]
Sounds like a good idea to me. I think we still need something in the file, either a raise or a comment or something, to explain why we have them, but I think they can live anywhere as long as they are complete and ship with the gem.

**Comment by blowmage** [comment]
How about a `README` file in the non-`/lib` directory?

**Comment by quartzmo** [comment]
Sounds good. Proposed name of the new directory?
