### ISSUE TITLE
Rethink Service .new constructor method

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#124]
As [discussed in #121](https://github.com/googleapis/gapic-generator-ruby/pull/121#issuecomment-487135543), we may want to rethink the convenience methods that are currently being created on the service module. For example, should this:

```ruby
Google::Showcase::V1alpha3::Echo.new #=> Google::Showcase::V1alpha3::Echo::Client
```

Be better named as this:

```ruby
Google::Showcase::V1alpha3::Echo.client #=> Google::Showcase::V1alpha3::Echo::Client
```

**Comment by dazuma** [comment]
For me, this is coming from the naming discussion where we consider `Google::Showcase::V1alpha3::Echo` as referring to the overall service (and `Google::Showcase::V1alpha3::Echo::Client` as referring to the client specifically). Then it seems misleading for `Google::Showcase::V1alpha3::Echo.new` to return a client.

**Comment by blowmage** [comment]
Would it be better to simply remove the service constructor? Remove `Google::Showcase::V1alpha3::Echo.new` in favor of using `Google::Showcase::V1alpha3::Echo::Client.new`?
