### ISSUE TITLE
Add Showcase Echo Wait test

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#131]

**Comment by jbolinger** [comment]
Is this still relevant? I ran the tests today and it seems that there is a test for `Wait` and it passes.

We do appear to be missing `Collect` though.

**Comment by blowmage** [comment]
Does the wait test do everything you want it to? There are no other RPCs defined on the wait service?

If so, then it looks like this issue can be closed.

**Comment by jbolinger** [comment]
The `Wait` test looks good to me. I just added a new `Block` method to the showcase Echo API that's meant for retry related tests but we'll have to wait for a release to use it.

Let's close this unless you had anything else in mind that you'd like to add to the existing `Wait` tests.

I'll send a PR to add the missing `Collect` test. Another minor thing I noticed is the missing Rubocop settings for the shared module - we might want to add it and reformat that stuff at some point for consistency when we do a doc pass or something.
