### ISSUE TITLE
Add Showcase Echo tests for Operations methods?

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#132]
Do we need this? Does the showcase server support it?

**Comment by jbolinger** [comment]
@blowmage could you clarify what you're looking for here?

Are you talking about [this](https://github.com/googleapis/gapic-showcase/blob/7e7576b29f7955d59a14a5eb68cab5ba28d31f3d/schema/google/showcase/v1beta1/echo.proto#L86)?

I have an open issue that I think is sort of related to this: https://github.com/googleapis/gapic-showcase/issues/66 that I'm planning to fix. So, if we have anything else that we'd like to see added to showcase let's talk about it now. Thoughts?

**Comment by blowmage** [comment]
> could you clarify what you're looking for here?

list_operations, get_operation, update_operation, delete_operation

**Comment by jbolinger** [comment]
Got it. I don't think this is supported now but I do think it's worth considering since we have special handling for it in all the libs. 

I'll open an issue to get other opinions in the showcase repo soon.

**Comment by jbolinger** [comment]
I added a simple implementation https://github.com/googleapis/gapic-showcase/pull/182. I'll add some tests here that use the new methods.

**Comment by jbolinger** [comment]
Done in #215.
