### ISSUE TITLE
Create google-cloud-configure gem

### ISSUE THREAD

**Issue by quartzmo** [googleapis/gapic-generator-ruby#175]
for shared config across cloud gems, Google::Cloud.configure do |c|
  # ...
end

We need to replace the config defined in google-cloud-core, but we want to use the same method name, so this may be -come tricky because we want apiary-based gems to be copatible *and* be configured the same way as gapic 2.0 gems.

**Comment by blowmage** [comment]
If we allow google-gax gems and gapic-common gems to be loaded at the same time, then there doesn't seem to be any reason to split the google-cloud-core gem apart.

**Comment by blowmage** [comment]
gapic-common defines a Config implementation that is separate from google-cloud-core's Config.
