### ISSUE TITLE
Use generator config file to control error retry

### ISSUE THREAD

**Issue by quartzmo** [googleapis/gapic-generator-ruby#176]
(we don't have any way to affect the generated code currently)

**Comment by jbolinger** [comment]
This was finally sorted out a few months ago, but I'm not sure if that news ever made its way here.

The key takeaway is that we'll allow the generator to, optionally, take a [service config file](https://github.com/grpc/grpc-proto/blob/master/grpc/service_config/service_config.proto) to control retry. At some unknown point in the future, the retry responsibilities should be overtaken by the grpc layer and we'll simply drop it from the generator. [Example reference implementation](https://github.com/googleapis/gapic-generator/pull/2859).

I'm not sure where we are at with migrating the config from the existing format to this format for the Cloud APIs, but at least the path is clear.

**Comment by noahdietz** [comment]
(Hi! Noticed this issue referencing my PR). I have a quick and dirty doc I can share (internally) about implementing support for this in a microgenerator, as well as more documentation on the decision/design process if that interests folks. Just ping me. Also, here is my https://github.com/googleapis/gapic-generator-go/pull/146 PR for this, if that helps at all as a reference.

**Comment by blowmage** [comment]
@noahdietz That would be great! Neither @quartzmo or myself are internal, but if you can pass that document to @jbolinger then he can relay the information to us.

**Comment by noahdietz** [comment]
I've sent a list of relevant docs to @jbolinger to be shared with y'all. Please lmk if I can help clarify anything or if you'd like to setup a GVC, happy to do so.

**Comment by viacheslav-rostovtsev** [comment]
fixed with https://github.com/googleapis/gapic-generator-ruby/pull/349
