### ISSUE TITLE
Separate timeout and deadline?

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#192]
The gRPC ClientStub take a `timeout` argument when constructed. The RPC method also takes a `deadline` argument for when the request should complete. Currently, we are calculating the deadline based off of the timeout. Therefore I pose the following questions?

* Do we want to continue with a default timeout of 60 seconds, as set in the generated GAPIC Client code and `ApiCall::Options`?
* Do we to set need both `timeout` and `deadline`? If a timeout is set on the client do we need to set one on the method call? Should we always set one or the other?
* Should we allow users to configure separate `timeout` and `deadline` values? Something like the following:

  ```ruby
  config = Google::Gax::Configuration.new do |c|
    # The timeout to set on the GRPC client
    c.add_field! :timeout, nil, match: [Numeric], allow_nil: true

    c.add_config! :methods do |methods|
      # The default deadline for all methods
      methods.add_field! :deadline, nil, match: [Numeric], allow_nil: true
      methods.add_config! :get_widget do |method|
        # The default deadline for the get_widget method
        method.add_field! :deadline, nil, match: [Numeric], allow_nil: true
      end
    end
  end
  ```

**Comment by blowmage** [comment]
in GRPC, `timeout` is a Numeric, and `deadline` is a `Time`. So `deadline` is `timeout` applied to `Time.now`. Currently we expose configuration for `timeout` at both the client level and the RPC level.

```ruby
Google::Cloud::Speech::V1.configure do |config|
  config.timeout = 60
  config.rpcs.recognize.timeout = 45
end
```

I think we should continue to use `timeout` for both in the configuration, but keep the two values separate. Meaning, client timeout is set on the GRPC client, and RPC timeout is set on the RPC calls. Currently, the RPC timeout "inherits" the client timeout value when one is not set. I think we should stop doing that. Thoughts?

**Comment by jbolinger** [comment]
If it isn't inherited what would the default `timeout` be for an RPC?

**Comment by blowmage** [comment]
If the client timeout is set, and the RPC timeout is not set, then GAPIC would create the GRPC client with the timeout value set, but would not sent deadline to the RPC calls.

Likewise, if the client timeout is not set set, but the RPC timeout is set, then GAPIC would create the GRPC client without setting the timeout value set, and would sent deadline to the RPC calls.

In other words, we should allow the GRPC client to do the correct thing and not over-specify the deadline behavior.

**Comment by blowmage** [comment]
If neither client timeout or RPC timeout are set, then the RPC should not timeout, which will benefit streaming RPCs.

**Comment by jbolinger** [comment]
Yeah, that sounds correct to me. I guess it would be simple to do something like `config.rpcs.each` to set a common timeout, which is the use case I had in mind.
