### ISSUE TITLE
GAPIC Common Utility Methods

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#205]
This is another naming question. Currently, we have a few utility methods that use modules defined under `Gapic::`

* `Gapic::Protobuf`
* `Gapic::Headers`

```ruby
request = Gapic::Protobuf.coerce request, to: SomeProtobufClass

metadata[:"x-goog-api-client"] ||= Gapic::Headers.x_goog_api_client *header_args
```

The question posed is whether these module names are confusing. These methods are global, and the modules they belong to are not intended to be included by other classes. Should those modules be renamed to make that more clear. The following has been proposed:

* `Gapic::ProtobufUtil`
* `Gapic::HeaderUtil`

```ruby
request = Gapic::ProtobufUtil.coerce request, to: SomeProtobufClass

metadata[:"x-goog-api-client"] ||= Gapic::HeaderUtil.x_goog_api_client *header_args
```

Is this a change worth making?

**Comment by blowmage** [comment]
In the google-cloud-* gems we have a common module named `Convert`, and that name hasn't been overly confusing.

```ruby
min_creation_time = Google::Cloud::Bigquery::Convert.time_to_millis Time.now
```

Because of this, I have a slight preference to keep the names in gapic-common as they are. But, if others do find these names confusing then I don't want to stand in the way of changing this. I would love to know what everyone thinks.

**Comment by jbolinger** [comment]
They are not confusing to me. Who proposed the change and what about it was confusing?

**Comment by blowmage** [comment]
There doesn't seem to be a consensus for renaming the existing utility modules/methods. Gonna close this.
