### ISSUE TITLE
Remove GAPIC Error classes

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#207]
The gapic-common error classes that wrap `GRPC::BadStatus` can be removed once the GPRC errors can be loaded without loading the GRPC C library. Once grpc/grpc#19893 has been released the GAPIC error classes can be removed.

**Comment by blowmage** [comment]
We have grpc changes to allow for this (grpc/grpc#19893 and grpc/grpc#19939), and they look like they won't be released until grpc version 1.24.0.

**Comment by dazuma** [comment]
This looks done.
