### ISSUE TITLE
Pick an API for first RC and ensure all configuration is available

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator-ruby#210]
Let's use this thread to track progress on the first Cloud gem to use the new and track any dependencies.

We need:
- [x] The API: [Speech](https://github.com/googleapis/googleapis/tree/master/google/cloud/speech/v1)
- [ ] Example [Configuration](https://github.com/googleapis/googleapis/tree/master/google/cloud/speech/v1/samples) (needs verification and blocked on #63)
- [ ] Retry Configuration
- [x] [Additional Configuration](https://github.com/googleapis/gapic-generator-ruby/blob/master/shared/config/speech.yml) (Ruby specific, not covered by spec)
- [ ] gapic-generator-ruby gem release

**Comment by dazuma** [comment]
Speech may be too complicated due to streaming (especially request-side). Considering Translate.

**Comment by blowmage** [comment]
Currently considering language and secret manager.
