### ISSUE TITLE
Generated unit tests contain invalid code

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator-ruby#220]
The generated unit tests have a few issues:
  + References to `MockSpeechCredentialsV1` (old hardcoded value)
  + Missing values i.e. `Gapic::Protobuf.coerce(name, to: )`

It may also be worth considering running the tests in `expected_output` during the `gen` task. Thoughts?

**Comment by blowmage** [comment]
This is being worked on.

**Comment by dazuma** [comment]
Verify if this is done

**Comment by blowmage** [comment]
This was partially implemented in #243 for non-streaming RPCs. @quartzmo is working on the streaming RPC tests.
