### ISSUE TITLE
Support google.api.resource_definition annotation

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator-ruby#244]
There is probably going to be a new annotation at the file level that we'll need to support all of Cloud API's resource names.

Details TBD - opening this to track it since it'll block some of the APIs.

**Comment by blowmage** [comment]
@jbolinger @dazuma Do we have any details on this? DId this new annotation happen?

**Comment by jbolinger** [comment]
@blowmage I haven't been following it, but I assume it did since there was as issue preventing some APIs from being migrated.

Have you checked for any updates here (or on the protos): https://aip.dev/client-libraries/4231

**Comment by blowmage** [comment]
Does this issue refer to the `google.api.resource_definition` annotation?

**Comment by jbolinger** [comment]
Yes, I think that's it.
