### ISSUE TITLE
Come up with a list of tasks related to sharing code between v1 and v2

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator-ruby#251]
- [x] Release google-cloud-errors 1.0
- [x] Add google-cloud-core gem dependency on google-cloud-errors to `~> 1.0`
- [x] Update cloud generator gemspec files to set google-cloud-errors dependency as `~> 1.0`
- [x] Release google-cloud-core 1.5 (with errors and config fixes)
- [x] Update veneer gem dependency on google-cloud-core to `~> 1.5`

**Comment by dazuma** [comment]
Initial list:
* Gax errors
* Configs

**Comment by blowmage** [comment]
### Release google-cloud-errors

Right now, the only thing that the cloud generator adds is a dependency on google-cloud-errors, and wrap all the GRPC::BadStatus errors raised by the RPC methods with a Google::Cloud::Error error object.

### Release google-cloud-core

All microgenerator configuration is implemented using the Config module in gapic-common. The changes in googleapis/google-cloud-ruby#4541 are needed for the gapic-common configuration objects to use the google-cloud-core configuration objects. We need a new core gem released and all microgenerator veneer gems updated to set the new version as the minimum.
