### ISSUE TITLE
Dynamically Generate Modules

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator-ruby#26]
## What
Inside [client.erb#L18](https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-generator-cloud/templates/cloud/client.erb#L18), the modules that the client is defined in are hard coded. These modules should be determined by the namespace of the service.

Similarly in [credentials.erb#L9](https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-generator-cloud/templates/cloud/credentials.erb#L9)

## Data
The data for the namespace can be access through the `Google::Gapic::Schema::Service#address` attribute. This address will return a list of strings in which the last string is the name of the service.

For speech this would look like: 
```rb
service.address # => ["google", "cloud", "speech", "v1", "Speech"]
```

## How
A solution would be to use [defaults/layouts/_ruby.erb](https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-generator/templates/default/layouts/_ruby.erb), passing in the namespaces and yielding the client body.

**Comment by blowmage** [comment]
This issue was referring to the old [client template](https://github.com/googleapis/gapic-generator-ruby/blob/c74380ae0c1a4a8c97bcfab6861521c5cba0945b/gapic-generator-cloud/templates/cloud/client.erb#L18) not using the ruby layout. But it does now.
