### ISSUE TITLE
Acceptance Tests

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#262]
The generator is currently not creating acceptance tests. The old gapic generator used configuration to define these tests, and only input we will have now is the sample tests. We should either drop acceptance tests in favor of the sample tests (yet to be implemented), or move the sample tests in the acceptance directory.

**Comment by dazuma** [comment]
I'm happy to drop the idea of acceptance tests in favor of sample tests (which will effectively perform the same function anyway). The configs that were used to generate acceptance tests under the old generator, are not going to come back.

**Comment by blowmage** [comment]
Closed by #290
