### ISSUE TITLE
Gemfile Changes

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#266]
- [ ] ~Update `gapic-common` github location to `gem "gapic-common", github: "googleapis/gapic-generator-ruby"`~
- [x] update rake gem version to `gem "rake", "~> 12.3"`
- [x] update minitest gem version to:
  ```
  # Pin minitest to 5.11.x to avoid warnings emitted by 5.12.
  # See https://github.com/googleapis/google-cloud-ruby/issues/4110
  gem "minitest", "~> 5.11.3"
  ```

**Comment by dazuma** [comment]
This looks done.
