### ISSUE TITLE
Update Cloud Language Configuration to match existing gem

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#267]
- [x] `.yardopts` title is wrong (not configured)
- [x] `.gemspec` description is wrong (not configured)
- [x] `.gemspec` summary is wrong (not configured)
- [x] `.gemspec` homepage is wrong (not configured)

**Comment by quartzmo** [comment]
The point of reverting the configuration to match the naming in the existing google cloud gem is to reduce noise in the diff of the google cloud PR.
