### ISSUE TITLE
Rubocop Configuration

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#270]
- [x] Exclude proto_docs directory
- [x] Add Naming/FileName exclude for dashed gem name (lib/google-cloud-language.rb)
- [x] Disable Style/CaseEquality for all files that define a Configure class. (verify if this is needed with google-style 1.24, because this is super useful in the configuration code and its stupid that rubocop enables this!)
- [x] Exclude Metrics/ClassLength for generated client.rb files. These files have the potential to have too many methods for the rules.
- [x] Exclude Metrics/LineLength for generated client.rb files. These files have the potential to have documentation strings too long for the rules. Excluding is easier than adding appropriate line breaks. (or we can generate the docs only in proto_docs instead...)

**Comment by dazuma** [comment]
@blowmage Can this be closed?
