### ISSUE TITLE
Rubocop Failures

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#273]
- [x] Credentials fails due to line length. This is because the template uses `%w()`, andd rubocop freaks out and reformats it with lines that are too long. use `[].freeze` with quoted strings instead. (verify using google-style 1.24)
- [x] Move suffix conditional `if parent_rpcs&.respond_to?` to prefix because line lengths

**Comment by dazuma** [comment]
@blowmage Can this be closed?
