### ISSUE TITLE
Dependency on Google Cloud Errors

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#274]
The cloud gems need to add a dependency on `google/cloud/errors`. This should either be the the google-cloud-core gem, or a new google-cloud-errors gem.

The dependency should be added to the cloud's generated gemspec file.

**Comment by blowmage** [comment]
@dazuma Should we put new emphasis on #177 so that the generated cloud gems only have to depend on google-cloud-errors instead all of google-cloud-core?

**Comment by dazuma** [comment]
Yes, I would prefer to break up google-cloud-core for the microgenerated libraries, and have separate google-cloud-config and google-cloud-errors gems.

**Comment by blowmage** [comment]
> have separate google-cloud-config and google-cloud-errors gems

Do you want the cloud gems to switch their configuration implementation from the one in gapic-common to the one in google-cloud-core/config?

**Comment by blowmage** [comment]
Closed by #300.
