### ISSUE TITLE
Dynamically determine helpers require path.

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator-ruby#28]
## What
In [client/_helpers.erb#L5](https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-generator-cloud/templates/cloud/client/_helpers.erb#L5) the require path for the client helpers should be dynamically determined. The path of the helpers should be based on the namespace of the service.

## Data
The data for the namespace can be access through the `Google::Gapic::Schema::Service#address` attribute. This address will return a list of strings in which the last string is the name of the service.

For speech this would look like: 
```rb
service.address # => ["google", "cloud", "speech", "v1", "Speech"]
```

## How
To generate this require path, simply join the service address on "/" without the final string.

**Comment by blowmage** [comment]
This has been implemented. Each client file has something similar to the following:

```ruby
# Once client is loaded, load helpers.rb if it exists.
begin
  require "google/cloud/speech/v1/speech/helpers"
rescue LoadError
end
```
