### ISSUE TITLE
The gem name provided to the gapic-generator-ruby has to match the package name specified in protos otherwise the VERSION constant is incorrectly referenced in the generated code

### ISSUE THREAD

**Issue by viacheslav-rostovtsev** [googleapis/gapic-generator-ruby#325]
previously called 
```
[Showcase] gapic-generator-cloud docker incorrectly places the Showcase::VERSION constant when generating showcase
```
the description on how to reproduce the bug at the end of this comment still applies but the issue is slightly wider.

The placement in the directory structure and modules generated for the `version.rb` file are governed by the `gem name` parameter supplied via the `<service>.yml` file in the CI tests or via the `--ruby-cloud-gem-name` parameter when generating with the docker image. ( See also https://github.com/googleapis/gapic-generator-ruby/issues/323 ). 

The placement of the service-level files is governed by the `package name` parameter, derived from the protobuf file, from the `package` parameter (or `ruby_package` option if provided). 

The `gem name` must partially map to the `package name`, e.g. for showcase `gem name` of  `google-showcase` maps to the `package name` from `package google.showcase.v1beta1` or for the grpc_service_config testing the `gem name` of `testing-grpc_service_config` will map to the `package name` from `option ruby_package = "Testing::GrpcServiceConfig";`. The mapping can be partial (excluding version).

If the mapping is wrong, like in the example below where we just give `showcase` as the gem name -- the `version.rb` file ends up in the wrong folder and the tests fail, unhelpfully.

----
Example of how to repro:

when generating showcase:
```sh
$ docker run --rm --user $UID \
  --mount type=bind,source=`pwd`/google/showcase/v1beta1,destination=/in/google/showcase/v1beta1,readonly \
  --mount type=bind,source=`pwd`/showcase-ruby,destination=/out \
  gcr.io/gapic-images/gapic-generator-ruby:latest --ruby-cloud-gem-name=showcase
```   
if we run tests with 
```sh
bundle exec rake ci
```

we get an error like this for every testing method:

```
Error:
Google::Showcase::V1beta1::Messaging::ClientTest#test_delete_room:                 
NameError: uninitialized constant Google::Showcase::VERSION                        
    /usr/local/google/home/virost/src/testplay/showcase-ruby/lib/google/showcase/v1beta1/messaging/client.rb:330:in `delete_room'                                      
    /usr/local/google/home/virost/src/testplay/showcase-ruby/test/google/showcase/v1beta1/messaging_test.rb:248:in `block in test_delete_room'            
```

There _is_ a VERSION constant in generated code:
```ruby
module Showcase
  VERSION = "0.0.1"
end
```
but it's in a file `/lib/showcase/version.rb` while the rest of the code is under `lib/google/showcase`.

**Comment by dazuma** [comment]
This is a good find. So:

* I believe the generator is correct in using the gem name to determine the actual location of `version.rb`, by Ruby convention. Thus, if the gem name actually is `showcase`, then `Showcase::VERSION` in `lib/showcase/version.rb` is correct.
* The gem name _should usually_ but _will not always_ map to the prefix of the package name. There will be exceptions related to branding concerns, etc.
* Therefore, the generator needs to be updated so that the references of the `VERSION` constant (I believe used during generation of the `X-Goog-API-Client` header) use the gem-name-derived namespace rather than the package-name-implied namespace.

**Comment by blowmage** [comment]
I agree that if the gem name is provided as `showcase` then the version constant should be defined as `Showcase::VERSION` in `lib/showcase/version.rb`.

**Comment by viacheslav-rostovtsev** [comment]
> I agree that if the gem name is provided as `showcase` then the version constant should be defined as `Showcase::VERSION` in `lib/showcase/version.rb`.
The good news is that is what is currently happening...

I've edited the issue title to correctly identify the problem; the placement of the constant seems to be correct, the references to it are not and that causes the breakage.
