### ISSUE TITLE
Allow running the plugin from github

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator-ruby#44]
I was trying to find a simple way to let people try out the generator and write a test script without downloading anything. This is the best method that I have found so far:

`Gemfile`
```ruby
#gem "gapic-generator", github: "googleapis/gapic-generator-ruby", branch: "master"
gem "gapic-generator", path: "../gapic-generator-ruby/gapic-generator"

gem "bundler", "~> 1.15"
gem "rake", "~> 10.0"
gem "grpc-tools", "~> 1.18"
```

`Rakefile`
```ruby
desc 'Generate showcase.'
task :generate_showcase do
  FileUtils.mkdir 'lib'

  command = []
  command << 'grpc_tools_ruby_protoc'
  command << '--ruby_out=lib'
  command << '--ruby_gapic_out=lib'
  command << '--proto_path ./proto/api-common-protos'
  command << '--proto_path ./proto/showcase'
  command << './proto/showcase/v1alpha3/echo.proto'
  full_command = command.join ' '

  sh full_command
end
```

The path version works fine, but the github version throws an error because of some files that are `.gitignore`'d.

```bash
$ bundle exec rake
<bunch of output>
loader.rb:17:in `require': cannot load such file -- google/api/annotations.pb (LoadError)
```

Is there a good way to ensure the github version works? Or, perhaps a better way to do this?

**Comment by blowmage** [comment]
AFAIK the only way to allow this is to check the generated `*.pb.rb` files into SCM. This was recently done for the common protos gems, and I think it would make sense for us to do something similar in this repo. That way these files would exist and the gem could be referenced either by path or github project.

Is this a change we should make?

**Comment by jbolinger** [comment]
If that change enables this I'm all for it. Also, if any of those generated protos are exposed and would be considered part of our API for customizations I'd be in favor of doing it for that reason as well.

**Comment by blowmage** [comment]
You can now add the gem by putting the following in a Gemfile:

```ruby
gem "gapic-generator", github: "googleapis/gapic-generator-ruby"
```
