### ISSUE TITLE
Generated test files do not have the auto-generated notice

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator-ruby#459]
Generated tests do not seem to have the expected notice:
```ruby
# Auto-generated by gapic-generator-ruby. DO NOT EDIT!
```

Add the comment, and check that it isn't missing from any other type of file.

**Comment by miraleung** [comment]
Using the cloud/vision example, I've checked that all auto-generated files now have the disclaimer after PR #462.
