### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator-ruby#491]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by hkdevandla** [comment]
@dazuma , friendly ping to take a look and fix it.

**Comment by hkdevandla** [comment]
Ping!

@viacheslav-rostovtsev , should this be on us (actools@) to enable this protection since we manage this repo? Please advice. We have to enable this otherwise it would gate Justin Beckwith's proposal to open up the googleapis/ for googlers. Thanks!

**Comment by SurferJeffAtGoogle** [comment]
Daniel, is there a reason to not enable branch protection today?

**Comment by dazuma** [comment]
It looks like someone already enabled it for this repo.
