### ISSUE TITLE
OAuth errors (e.g. from invalid token) surface as GRPC::Unavailable, but some of them (e.g. Signet:AuthorizationError on presenting an expired refresh token) are clearly unretriable. Should something be done about this?

### ISSUE THREAD

**Issue by viacheslav-rostovtsev** [googleapis/gapic-generator-ruby#525]
https://github.com/googleads/google-ads-ruby/issues/246 for details. The question is whether error wrapping is working as intended.

**Comment by viacheslav-rostovtsev** [comment]
This seems to be an intended GRPC behaviour, interestingly enough.

` it 'should receive UNAVAILABLE if call credentials plugin fails' `
https://github.com/grpc/grpc/blob/95ab12cf8fca2d92b4a097369dd8249cf8997b9f/src/ruby/spec/generic/client_stub_spec.rb#L239
The PR that introduced this behaviour with the original reasoning (circa 2017): https://github.com/grpc/grpc/pull/13322

On whether it's a bug in gapic-generator-ruby
- gapic generated libraries do not unwrap/rewrap the errors, so they surface the `UNAVAILABLE` they get from the GRPC.

On potential mitigation
- updating retry policy for google-ads-ruby provides mitigation for this (and makes sense in any case)
- we can try probing all `UNAVAILABLE` for containing `Signet::AuthorizationError` and converting them to `UNATHENTICATED`. 
    * Signet seems to be returning different status codes when server experiencing issues versus when a genuine authorization error occurs: 
       (it "should raise a remote server error if the server gives a 5xx status", it "should raise an unexpected error if the token server gives an unexpected status" --  
        https://github.com/googleapis/signet/blob/cd5d2792055e99e188b81a4210e717ddb4071fa3/spec/signet/oauth_2/client_spec.rb#L567)
- more generically there could be a mechanism to tell a client library: """ treat these errors from my auth plugin' as `UNATHENTICATED` when received inside `UNAVAILABLE` """
   * might be too complicated

I'll try to figure out if this impacts Cloud libraries as well.

**Comment by viacheslav-rostovtsev** [comment]
@dazuma because it's interesting

**Comment by aohren** [comment]
grpc/grpc#13322 mentions "auth metadata". Does metadata have any specific meaning in this context? I'm wondering if there's a semantic difference between a "metadata failure" and an auth failure due to invalid / expired / unauthorized access/refresh token.

**Comment by viacheslav-rostovtsev** [comment]
They do have a test that returns UNAUTHENTICATED at https://github.com/jboeuf/grpc/blob/master/test/cpp/end2end/end2end_test.cc#L1813 but I am not exactly sure what's the difference atm.
