### ISSUE TITLE
User subclasses of Credentials not getting defaults

### ISSUE THREAD

**Issue by quartzmo** [googleapis/gapic-generator-ruby#534]
The micro-generator changed the way that default values are set in `Credentials`, breaking instances of subclasses of the generated `Credentials` classes.  See googleapis/google-cloud-ruby#8610.

In the [old generated clients](https://github.com/googleapis/google-cloud-ruby/blob/google-cloud-pubsub/v1.10.0/google-cloud-pubsub/lib/google/cloud/pubsub/v1/credentials.rb#L23), the default scope was set as follows:

```
          SCOPE = ["https://www.googleapis.com/auth/pubsub"].freeze
```

This generator changed this statement to the following for [new generated clients](https://github.com/googleapis/google-cloud-ruby/blob/google-cloud-pubsub/v2.3.1/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/credentials.rb#L28-L31):

```
            self.scope = [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/pubsub"
            ]
```

The class instance variables set in `Google::Auth::Credentials.scope=`, `Google::Auth::Credentials.env_vars=` and `Google::Auth::Credentials.paths=` are not visible to `Google::Auth::Credentials` when those methods are called by a subclass. Thus we get the error documented in  googleapis/google-cloud-ruby#8610. Setting the class constants works because of lookups like this one in [`Google::Auth::Credentials.scope`](https://github.com/googleapis/google-auth-library-ruby/blob/master/lib/googleauth/credentials.rb#L194).

The commit message for [the change](https://github.com/googleapis/gapic-generator-ruby/commit/2dd6ff3153adb8260e739a7ce28a6ee51be03d8e#diff-0d4c9bdc29cb7a773d30cfc52e5d2ec1a0aa15b46792e234a4d5b3e43a8a747f) says simply "Use methods to set cloud Credentials values". I don't think the error behavior was intended.

**Comment by dazuma** [comment]
This was fixed in the googleauth gem instead. (See https://github.com/googleapis/google-auth-library-ruby/pull/284)
