### ISSUE TITLE
bazel: move description & title protoc options to attributes

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-ruby#539]
If the values of `ruby-cloud-description` or `ruby-cloud-title` have spaces in them (which is highly likely) and these options are supplied to `extra_protoc_parameters` in a `BUILD.bazel`, re-generation (via `build_gen`) of an existing `BUILD.bazel` file results in the values of `ruby-cloud-description` and `ruby-cloud-title` being expanded and supplied as `extra_protoc_parameters` which breaks the build. 

[Example BUILD.bazel](https://github.com/googleapis/googleapis/blob/c71a9c4ff7bc5179f2e94af31bc95ce4922575ff/google/cloud/channel/v1/BUILD.bazel#L289-L290). From googleapis, reproduce the issue by running  `bazel run //:build_gen -- --src=google/cloud/channel/v1` and attempt to build the `ruby_gapic_library` target: `bazel build //google/cloud/channel/v1:channel_ruby_gapic`.

While this doesn't sound like an issue gapic-generator-ruby should deal with, it is infeasible to fix in `build_gen` at the moment, because the `buildozer` API for merging `BUILD.bazel` files does not support `List` attributes (like `extra_protoc_parameters`) very well (it just puts all the items into a single, square brace-wrapped, space-delimited string).

So, this is a request to add a `description` and `title` attribute to `ruby_gapic_library` that would subsequently be added to generator invocation as `ruby-cloud-description={value}` and `ruby-cloud-title={value}"`. We could then have `build_gen` preserve these individual attributes on `ruby_gapic_library`, which for singular `String` attributes works much better.

WDYT?

cc @alexander-fenster

**Comment by viacheslav-rostovtsev** [comment]
This looks like a reasonable straightforward thing to do.
