### ISSUE TITLE
Restore Credentials

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#57]
PR #56 moved credentials to be at the service level (Google::Cloud::Speech::V1::Speech::Credentials`) rather than at the package level (Google::Cloud::Speech::V1::Credentials`). Do we want to move the Credentials object back to the previous location? It is possible for different services in the same package to define a different set of OAuth scopes, although we don't know how likely that is. If that is the case, we will need a way to determine all the scopes used by all the services in the same package and set them on the Credentials class.

Another problem is that the Rakefile currently uses the old Credentials object to clear environment variables when running acceptance tests. But we could work around this fairly easily.

**Comment by blowmage** [comment]
Do we still think Credentials should be placed at the package level `Google::Cloud::Speech::V1` as well as the service level `Google::Cloud::Speech::V1::Speech`?

Veneer gems like Datastore place Credentials at the gem level `Google::Cloud::Datastore`, but those Credentials are separate from the GAPIC Credentials.

I think the current placement at the service level makes the most sense.

**Comment by jbolinger** [comment]
I think we can stick with the service level, as you suggest. If we were to put it at the package level it would need some rework for exactly the reasons you mentioned (scopes), but I don't see a need for this right now so I think we safely can defer it.
