### ISSUE TITLE
Client path helpers as instance methods

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#6]
The previous GAPIC client had class-level path helper methods, and we want to support them as instance methods. See googleapis/google-cloud-ruby#2515 as an example.

**Comment by TheRoyalTnetennba** [comment]
Another example of this is https://github.com/googleapis/google-cloud-ruby/blob/a852d8552fc9b7a10d7482b50a3f56ee5daacba7/google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb#L131

**Comment by blowmage** [comment]
Fixed in #93.
