### ISSUE TITLE
Add FieldPresenter test

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#65]

**Comment by jbolinger** [comment]
@blowmage feel free to add what's still missing after #217 and I can probably pick this one up and close it out if you'd like.

**Comment by dazuma** [comment]
We still may need to flesh out more test cases from the garbage protos.

**Comment by dazuma** [comment]
verify that this is fully complete

**Comment by blowmage** [comment]
We have tests https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-generator/test/gapic/presenters/field_presenter_test.rb and https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-generator/test/gapic/presenters/field_presenter_showcase_test.rb.
