### ISSUE TITLE
Some Yard cross-reference links don't honor namespace-override

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator-ruby#678]
See @quartzmo 's comments in https://github.com/googleapis/google-cloud-ruby/pull/14062 for an example.

**Comment by noahdietz** [comment]
(coming from issue triage rotation) Any update on this? Has it been planned/fixed? I will downgrade the priority for now since it has remained quiet, it must not be as important anymore.

**Comment by dazuma** [comment]
Working on a fix

**Comment by dazuma** [comment]
Confirmed fixed in generator 0.15.0.
