### ISSUE TITLE
How do we use the method_signatures annotation?

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#68]
The `method_signatures` annotations allow for nested arguments, but how does this work with Ruby?

**Comment by blowmage** [comment]
So far, we are not considering this annotation. We are accepting either the request object as a positional argument, the request values in a Hash as a positional argument, or the request values as named arguments.

We might consider the annotation for documentations purposes.

**Comment by blowmage** [comment]
We probably aren't going to use `method_signatures`, and stay with `request` and `options` positional arguments.

**Comment by jbolinger** [comment]
It seems like we've made the decision at this point. Is there any reason to keep this open?
