### ISSUE TITLE
Add path helper methods

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#76]
We need to add the path helper methods to the Client class. We should add both class methods and instance methods.

**Comment by blowmage** [comment]
@dazuma You had at one point asked that we move to named arguments. The current path helper methods use positional arguments. Is moving to named arguments still something we want to do for these methods?

**Comment by blowmage** [comment]
Or should we support users to specify one or the other via configuration?

**Comment by jbolinger** [comment]
This is timely. During our review today there was an alternative suggestion to add these as module(s) that could be mixed in where needed. @landrito is trying to work out what that would look like - let's give him a little time to process the feedback and then we can figure out the best way to add these.

**Comment by blowmage** [comment]
It should be pretty easy to do.

```ruby
module FooHelpers
  def foo_path foo
    "foos/#{foo}"
  end
end

class FooClient
  extend FooHelpers
  include FooHelpers
end

FooClient.foo_path "bar" #=> "foos/bar"
FooClient.new.foo_path "baz" #=> "foos/baz"
```

**Comment by dazuma** [comment]
Yes, that's exactly what was being suggested.

**Comment by blowmage** [comment]
Also #6.
