### ISSUE TITLE
Consistent use for blocks given to client method calls

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator-ruby#85]
Client method signatures were redesigned in #82, but the `block` argument remains unchanged and is inconsistent across method types.

For example, if a `block` is given to a normal unary request it is passed on to the underlying API callable and exposes the raw gRPC operation to the caller. For an LRO operation, the block is instead used for the LRO's `on_done` instead, and it is ignored for server methods. Should this be made consistent across method types?

**Comment by blowmage** [comment]
I am always :+1: for added consistency. 😁 If the LRO block worked like the normal blocks, I think users could still be able to configure the `on_done` callback. They would just have to add it to the object passes to the method's block instead.

I don't know how to support the block for streaming methods however.

**Comment by jbolinger** [comment]
I'd be +1 for make the LRO and normal methods consistent. I forget how it works for paged methods though so we need to think through that case too. The intent for the block was to give the caller a way to access the gRPC operation, so I think it should work the same but it would have to be repeated.

I'm not sure about streaming methods either. One idea would be to use a block to allow the caller to pass through to the raw gRPC interface for streaming and bypass the helpers that we plan to build on streaming methods. For the common case, without the block, they would use the helpers.

**Comment by blowmage** [comment]
I can definitely see adding the options to pass a block to server and bidi methods instead of returning an enumerable. It would add support using blocks with server/bidi methods, but it wouldn't be consistent with how those blocks are used with unary/lro/client methods.

**Comment by blowmage** [comment]
Some of these changes are made in #94.

**Comment by blowmage** [comment]
#108 makes the LRO block usage consistent and adds blocks for server and bidi streaming methods. All methods now use blocks.

**Comment by blowmage** [comment]
As of #143 all method blocks are consistent.
