### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-ruby#944]
The `README.md` file says "This project is a preview. Please try it out and let us know what you think, but there are currently no guarantees of stability or support." and "This tool is in pre-alpha so it is not yet released to RubyGems. You will have to build the generator from scratch."

The latter does not seem to be true: https://rubygems.org/search?query=gapic-generator

Maybe it's worth checking that the info in the `README` is up to date?

**Comment by shivgautam** [comment]
Readme updated.
